@startuml

!define Class agent
!define ExternalClass agent
!define Property usecase

skinparam Property {
BackgroundColor LightBlue
BorderColor Black
  ArrowColor Black
  linetype Ortho
}

skinparam Class {
BackgroundColor LightGreen
BorderColor Black
ArrowColor Black
linetype Ortho
}


Class Dataset
Class Action
Class CreateAction
Class DefinedTerm
Class dbpedia_Satellite as "dbpedia:Satellite" #orange 
Class dbpedia_Scientific_instrument as "dbpedia:Scientific_instrument" #orange






' using blanks inside () creates separate objects

Dataset -up-> (URL) : "measurementTechnique"
Dataset -down-> (Text) : "measurementTechnique"

CreateAction .up.|> Action

CreateAction -right-> DefinedTerm : "instrument"

Dataset -right-> CreateAction : "potentialAction"

DefinedTerm <.[dotted].>  dbpedia_Satellite

DefinedTerm <.[dotted].>  dbpedia_Scientific_instrument










@enduml