@startuml

!define Class agent
!define Property usecase

skinparam Property {
BackgroundColor LightBlue
BorderColor Black
  ArrowColor Black
  linetype Ortho
}

skinparam Class {
BackgroundColor LightGreen
BorderColor Black
ArrowColor Black
linetype Ortho
}

Class Dataset
Class Organization
Class Person
Class Role
Class CreativeWork

CreativeWork <|-up- Dataset

CreativeWork -right-> Organization : "(creator),\n(contributor),\n(author),\npublisher,\nprovider"

CreativeWork -left-> Person : "creator,\ncontributor,\n(author),\n(publisher),\n(provider)"
CreativeWork --> Role : "creator,\ncontributor,\n(author),\npublisher,\nprovider"



@enduml