@startuml

!define Class agent
!define Property usecase

skinparam Property {
BackgroundColor LightBlue
BorderColor Black
  ArrowColor Black
  linetype Ortho
}

skinparam Class {
BackgroundColor LightGreen
BorderColor Black
ArrowColor Black
linetype Ortho
}

Class Dataset
Class ListItem
Class Language
Class CreativeWork

Dataset -up-|> CreativeWork

CreativeWork -up-> ListItem : "subjectOf"

ListItem -up-> (DateTime) : "dateCreated,\ndateModified,\ndatePublished"

ListItem -up-> (Date) : "dateCreated,\ndateModified,\ndatePublished"

ListItem -right-> (Text) : "inLanguage,\nencodingFormat"

ListItem -up-> (URL) : "encodingFormat"

ListItem -left-> Language : "inLanguage"




@enduml