@startuml

!define Class agent
!define Property usecase

skinparam Property {
BackgroundColor LightBlue
BorderColor Black
  ArrowColor Black
  linetype Ortho
}

skinparam Class {
BackgroundColor LightGreen
BorderColor Black
ArrowColor Black
linetype Ortho
}

Class Dataset
Class Organization
Class PostalAddress



Dataset -right-> Organization : "publisher,\nprovider"

Organization -right-> PostalAddress : "address"

Organization -down-> (URL) : "url"
Organization -down-> (Text) : "name,\ntelephone,\nfaxNumber,\nemail"


@enduml