@startuml

!define Class agent
!define Property usecase

skinparam Property {
BackgroundColor LightBlue
BorderColor Black
  ArrowColor Black
  linetype Ortho
}

skinparam Class {
BackgroundColor LightGreen
BorderColor Black
ArrowColor Black
linetype Ortho
}

Class Organization
Class PostalAddress
Class Person
Class PropertyValue

Person -right-> PostalAddress : "address"

Person -down-> (URL) : "@id,\nurl,\nsameAs"
Person -down-> (Text) : "name,\nfamilyName,\ngivenName,\ntelephone,\nfaxNumber,\nemail"

Person -up-> Organization: "affiliation,\nmemberOf"

Person -left-> PropertyValue : "identifier"


@enduml