@startuml

!define Class agent
!define Property usecase

skinparam Property {
BackgroundColor LightBlue
BorderColor Black
  ArrowColor Black
  linetype Ortho
}

skinparam Class {
BackgroundColor LightGreen
BorderColor Black
ArrowColor Black
linetype Ortho
}

Class Dataset
Class DataDownload
Class MediaObject
Class Action
Class LinkRole

Dataset -down-> LinkRole : "url,\nthumbnailUrl"

Dataset -down-> (URL) : "url,\nthumbnailUrl"

Dataset -right-> MediaObject : "subjectOf,\nmentions"

Dataset -left-> DataDownload : "distribution"

Dataset -up-> Action : "potentialAction"




@enduml